"""Cartographic figures: prediction, uncertainty and spatial SHAP maps.

Every map produced here carries a title, a colour bar, a north arrow (only when the grid is
north-up, otherwise omitted rather than drawn misleadingly), a scale bar, labelled
coordinate axes, and a footnote with CRS and data source. SHAP maps use a diverging colour
map that is symmetric about zero.
"""

from __future__ import annotations

import math
from collections.abc import Sequence
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import BoundaryNorm, ListedColormap, TwoSlopeNorm
from matplotlib.patches import Patch
from matplotlib.ticker import FuncFormatter

from ..io.raster import RasterStack
from .style import (
    DIVERGING_CMAP,
    QUALITATIVE,
    SEQUENTIAL_CMAP,
    UNCERTAINTY_CMAP,
    apply_style,
    save_figure,
)

SOURCE_SYNTHETIC = "Synthetic data generated by GeoExplain (not real observations)"


# --------------------------------------------------------------------------- map furniture
def _crs_info(reference: RasterStack) -> dict[str, Any]:
    """Return unit information for axis labels and scale bars."""
    info = {"geographic": False, "meters_per_unit": 1.0, "label": None}
    crs = reference.crs
    if crs is None:
        return info
    try:
        import pyproj

        pcrs = pyproj.CRS.from_user_input(crs.to_wkt() if hasattr(crs, "to_wkt") else crs)
        info["label"] = pcrs.to_string()
        if pcrs.is_geographic:
            info["geographic"] = True
        else:
            info["meters_per_unit"] = float(pcrs.axis_info[0].unit_conversion_factor)
    except Exception:  # noqa: BLE001
        info["label"] = reference.crs_string
    return info


def _nice_length(target: float) -> float:
    """Largest 1/2/5 x 10^k value not exceeding ``target``."""
    if target <= 0:
        return 0.0
    exp = 10 ** math.floor(math.log10(target))
    for mult in (5, 2, 1):
        if mult * exp <= target:
            return mult * exp
    return exp


def add_north_arrow(ax: plt.Axes, loc: tuple[float, float] = (0.93, 0.90), size: float = 0.09) -> None:
    """Draw a simple north arrow in axes coordinates (valid for north-up grids only)."""
    x, y = loc
    ax.annotate(
        "",
        xy=(x, y),
        xytext=(x, y - size),
        xycoords="axes fraction",
        arrowprops={"arrowstyle": "-|>", "color": "black", "lw": 1.4, "mutation_scale": 12},
        zorder=6,
    )
    ax.text(x, y + 0.012, "N", transform=ax.transAxes, ha="center", va="bottom", fontsize=9,
            fontweight="bold", zorder=6)


def add_scale_bar(ax: plt.Axes, reference: RasterStack, fraction: float = 0.25) -> str | None:
    """Add a two-segment scale bar (metres/kilometres) to the lower-left of ``ax``.

    For geographic CRSs the length is approximated at the map-centre latitude.
    """
    info = _crs_info(reference)
    left, bottom, right, top = reference.bounds
    width_units = right - left
    if info["geographic"]:
        lat = 0.5 * (bottom + top)
        metres_per_unit = 111_320.0 * math.cos(math.radians(lat))
    else:
        metres_per_unit = info["meters_per_unit"]
    total_m = _nice_length(width_units * metres_per_unit * fraction)
    if total_m <= 0:
        return None
    length_units = total_m / metres_per_unit
    x0 = left + 0.05 * width_units
    y0 = bottom + 0.06 * (top - bottom)
    seg = length_units / 2
    h = 0.012 * (top - bottom)
    ax.add_patch(plt.Rectangle((x0, y0), seg, h, fc="black", ec="black", lw=0.6, zorder=6))
    ax.add_patch(plt.Rectangle((x0 + seg, y0), seg, h, fc="white", ec="black", lw=0.6, zorder=6))
    label = f"{total_m / 1000:g} km" if total_m >= 1000 else f"{total_m:g} m"
    ax.text(x0 + length_units / 2, y0 + 2.2 * h, label, ha="center", va="bottom", fontsize=8,
            zorder=6, bbox={"fc": "white", "ec": "none", "alpha": 0.6, "pad": 1.0})
    if info["geographic"]:
        return f"{label} (approximate, at map-centre latitude)"
    return label


def _format_axes(ax: plt.Axes, reference: RasterStack, show_labels: bool = True, inset_ticks: bool = False) -> None:
    info = _crs_info(reference)
    left, bottom, right, top = reference.bounds
    ax.set_xlim(left, right)
    ax.set_ylim(bottom, top)
    ax.set_aspect("equal")
    if info["geographic"]:
        xl, yl, fmt = "Longitude (°)", "Latitude (°)", FuncFormatter(lambda v, _: f"{v:.3f}")
    else:
        unit = "m" if abs(info["meters_per_unit"] - 1.0) < 1e-9 else "map units"
        xl, yl = f"Easting ({unit})", f"Northing ({unit})"
        fmt = FuncFormatter(lambda v, _: f"{v:,.0f}")
    ax.xaxis.set_major_formatter(fmt)
    ax.yaxis.set_major_formatter(fmt)
    ax.locator_params(axis="x", nbins=4, prune="lower")
    ax.locator_params(axis="y", nbins=4)
    ax.tick_params(axis="x", rotation=0, labelsize=7)
    ax.tick_params(axis="y", labelsize=7)
    if inset_ticks:
        ax.set_xticks([left, 0.5 * (left + right), right])
        ax.set_yticks([bottom, 0.5 * (bottom + top), top])
        xl_ = ax.get_xticklabels()
        xl_[0].set_ha("left")
        xl_[-1].set_ha("right")
    for label in ax.get_yticklabels():
        label.set_rotation(90)
        label.set_va("center")
    if inset_ticks:
        yl_ = ax.get_yticklabels()
        yl_[0].set_ha("center")
        yl_[0].set_va("bottom")
        yl_[-1].set_va("top")
    if show_labels:
        ax.set_xlabel(xl, fontsize=8)
        ax.set_ylabel(yl, fontsize=8)
    for spine in ax.spines.values():
        spine.set_visible(True)
        spine.set_linewidth(0.8)


def _footnote(fig: plt.Figure, reference: RasterStack, source: str, extra: str = "") -> None:
    info = _crs_info(reference)
    crs_txt = info["label"] or reference.crs_string or "unknown CRS"
    txt = f"CRS: {crs_txt}.  Source: {source}."
    if extra:
        txt += f"  {extra}"
    fig.text(0.01, -0.005, txt, fontsize=6.5, color="#444444", ha="left", va="top", wrap=True)


def _draw_layer(
    ax: plt.Axes,
    array: np.ndarray,
    reference: RasterStack,
    cmap: Any,
    norm: Any = None,
    vmin: float | None = None,
    vmax: float | None = None,
) -> Any:
    left, bottom, right, top = reference.bounds
    masked = np.ma.masked_invalid(np.asarray(array, dtype=float))
    cm = plt.get_cmap(cmap).copy() if isinstance(cmap, str) else cmap
    cm.set_bad("#F2F2F2")
    kwargs: dict[str, Any] = {"cmap": cm, "extent": (left, right, bottom, top), "origin": "upper",
                              "interpolation": "nearest"}
    if norm is not None:
        kwargs["norm"] = norm
    else:
        kwargs.update(vmin=vmin, vmax=vmax)
    return ax.imshow(masked, **kwargs)


def _symmetric_limit(arrays: Sequence[np.ndarray], percentile: float = 99.0) -> float:
    vals = np.concatenate([np.abs(a[np.isfinite(a)]).ravel() for a in arrays])
    lim = float(np.percentile(vals, percentile)) if vals.size else 1.0
    return lim if lim > 0 else 1.0


# --------------------------------------------------------------------------- single maps
def plot_map(
    array: np.ndarray,
    reference: RasterStack,
    title: str,
    cbar_label: str,
    cmap: str = SEQUENTIAL_CMAP,
    diverging: bool = False,
    vmin: float | None = None,
    vmax: float | None = None,
    source: str = SOURCE_SYNTHETIC,
    path: str | Path | None = None,
    formats: Sequence[str] = ("png",),
    figsize: tuple[float, float] = (6.4, 5.6),
    note: str = "",
) -> plt.Figure:
    """Plot one raster layer as a complete map.

    ``diverging=True`` centres the colour scale on zero symmetrically (use for SHAP values).
    The figure is saved when ``path`` is given.
    """
    apply_style()
    fig, ax = plt.subplots(figsize=figsize)
    if diverging:
        lim = vmax if vmax is not None else _symmetric_limit([array])
        norm = TwoSlopeNorm(vmin=-lim, vcenter=0.0, vmax=lim)
        im = _draw_layer(ax, array, reference, cmap if cmap != SEQUENTIAL_CMAP else DIVERGING_CMAP, norm=norm)
    else:
        im = _draw_layer(ax, array, reference, cmap, vmin=vmin, vmax=vmax)
    _format_axes(ax, reference)
    ax.set_title(title, loc="left")
    cbar = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.03)
    cbar.set_label(cbar_label, fontsize=8)
    cbar.ax.tick_params(labelsize=7)
    if reference.is_north_up:
        add_north_arrow(ax)
    add_scale_bar(ax, reference)
    _footnote(fig, reference, source, note)
    if path is not None:
        save_figure(fig, path, formats=formats, close=False)
    return fig


def plot_shap_map(
    result: Any,
    feature: str,
    path: str | Path | None = None,
    source: str = SOURCE_SYNTHETIC,
    formats: Sequence[str] = ("png",),
    vmax: float | None = None,
) -> plt.Figure:
    """Map of the spatial contribution of one feature (from a ``SpatialShapResult``)."""
    label = result.feature_labels.get(feature, feature)
    space = result.shap.output_space
    title = f"Spatial contribution of {label} to the predicted {_target_phrase(result)}"
    unit = f"SHAP value ({space} units)"
    return plot_map(
        result.layers[feature], result.stack, title, unit, diverging=True, vmax=vmax, source=source,
        path=path, formats=formats,
        note="Red: raises the prediction; blue: lowers it, relative to the model base value. "
        "Describes the model, not causal effects.",
    )


def _target_phrase(result: Any) -> str:
    cfg = getattr(result, "model_config", {}) or {}
    return "probability" if cfg.get("task") == "classification" else "value"


# --------------------------------------------------------------------------- panels
def plot_shap_panels(
    result: Any,
    path: str | Path | None = None,
    features: Sequence[str] | None = None,
    ncols: int = 4,
    source: str = SOURCE_SYNTHETIC,
    formats: Sequence[str] = ("png",),
) -> plt.Figure:
    """Grid of spatial SHAP maps with one shared, zero-centred colour scale.

    A common scale keeps panels comparable: differences in colour intensity reflect real
    differences in contribution magnitude between features.
    """
    apply_style()
    feats = list(features or result.feature_names)
    n = len(feats)
    ncols = min(ncols, n)
    nrows = math.ceil(n / ncols)
    fig, axes = plt.subplots(nrows, ncols, figsize=(3.1 * ncols + 0.6, 3.0 * nrows + 0.5), squeeze=False)
    lim = _symmetric_limit([result.layers[f] for f in feats])
    norm = TwoSlopeNorm(vmin=-lim, vcenter=0.0, vmax=lim)
    im = None
    for i, ax in enumerate(axes.flat):
        if i >= n:
            ax.axis("off")
            continue
        im = _draw_layer(ax, result.layers[feats[i]], result.stack, DIVERGING_CMAP, norm=norm)
        _format_axes(ax, result.stack, show_labels=False, inset_ticks=True)
        ax.set_title(result.feature_labels.get(feats[i], feats[i]), fontsize=9)
        if i % ncols != 0:
            ax.set_yticklabels([])
        if i < n - ncols:
            ax.set_xticklabels([])
        if i == 0:
            if result.stack.is_north_up:
                add_north_arrow(ax, loc=(0.9, 0.88), size=0.12)
            add_scale_bar(ax, result.stack, fraction=0.3)
    fig.suptitle("Spatial SHAP: where each feature raises or lowers the prediction", x=0.01, ha="left",
                 fontsize=11, fontweight="bold")
    cbar = fig.colorbar(im, ax=axes, fraction=0.025, pad=0.02, shrink=0.85)
    cbar.set_label(f"SHAP value ({result.shap.output_space} units)", fontsize=8)
    cbar.ax.tick_params(labelsize=7)
    _footnote(fig, result.stack, source, "Shared symmetric colour scale; positive (red) raises the prediction.")
    if path is not None:
        save_figure(fig, path, formats=formats, close=False)
    return fig


def plot_dominant_driver(
    result: Any,
    path: str | Path | None = None,
    source: str = SOURCE_SYNTHETIC,
    formats: Sequence[str] = ("png",),
    ax: plt.Axes | None = None,
) -> plt.Figure:
    """Categorical map of the feature with the largest absolute SHAP value in each cell."""
    apply_style()
    names = result.feature_names
    colors = [QUALITATIVE[i % len(QUALITATIVE)] for i in range(len(names))]
    own_fig = ax is None
    fig, ax = plt.subplots(figsize=(6.4, 5.6)) if own_fig else (ax.figure, ax)
    dom = np.where(result.dominant >= 0, result.dominant, np.nan).astype(float)
    cmap = ListedColormap(colors)
    norm = BoundaryNorm(np.arange(-0.5, len(names) + 0.5, 1), cmap.N)
    _draw_layer(ax, dom, result.stack, cmap, norm=norm)
    _format_axes(ax, result.stack)
    ax.set_title("Dominant driver (largest |SHAP| per cell)", loc="left")
    handles = [Patch(fc=c, ec="none", label=result.feature_labels.get(n, n)) for n, c in zip(names, colors, strict=False)]
    ax.legend(handles=handles, loc="center left", bbox_to_anchor=(1.02, 0.5), title="Feature", fontsize=7)
    if result.stack.is_north_up:
        add_north_arrow(ax)
    add_scale_bar(ax, result.stack)
    if own_fig:
        _footnote(fig, result.stack, source, "Dominance describes model reliance, not causal importance.")
        if path is not None:
            save_figure(fig, path, formats=formats, close=False)
    return fig


def plot_prediction_uncertainty(
    result: Any,
    path: str | Path | None = None,
    source: str = SOURCE_SYNTHETIC,
    formats: Sequence[str] = ("png",),
) -> plt.Figure:
    """Three-panel figure: prediction, uncertainty (if available) and dominant driver."""
    apply_style()
    has_unc = result.uncertainty is not None
    ncols = 3 if has_unc else 2
    fig, axes = plt.subplots(1, ncols, figsize=(4.6 * ncols, 4.4))
    axes = np.atleast_1d(axes)
    cls = _target_phrase(result)
    im0 = _draw_layer(axes[0], result.prediction, result.stack, SEQUENTIAL_CMAP, vmin=0 if cls == "probability" else None,
                      vmax=1 if cls == "probability" else None)
    _format_axes(axes[0], result.stack)
    axes[0].set_title("(a) Model prediction", loc="left")
    fig.colorbar(im0, ax=axes[0], fraction=0.046, pad=0.03).set_label(
        "Predicted probability" if cls == "probability" else "Predicted value", fontsize=8)
    idx = 1
    if has_unc:
        im1 = _draw_layer(axes[1], result.uncertainty, result.stack, UNCERTAINTY_CMAP)
        _format_axes(axes[1], result.stack)
        axes[1].set_title(f"(b) Uncertainty ({result.uncertainty_method})", loc="left")
        fig.colorbar(im1, ax=axes[1], fraction=0.046, pad=0.03).set_label(result.uncertainty_method, fontsize=8)
        idx = 2
    plot_dominant_driver(result, ax=axes[idx])
    axes[idx].set_title(f"({'c' if has_unc else 'b'}) Dominant driver", loc="left")
    if result.stack.is_north_up:
        add_north_arrow(axes[0])
    add_scale_bar(axes[0], result.stack)
    note = result.uncertainty_description or ""
    _footnote(fig, result.stack, source, note)
    fig.tight_layout()
    if path is not None:
        save_figure(fig, path, formats=formats, close=False)
    return fig


def plot_feature_and_shap(
    result: Any,
    feature: str,
    path: str | Path | None = None,
    source: str = SOURCE_SYNTHETIC,
    formats: Sequence[str] = ("png",),
) -> plt.Figure:
    """Side by side: the input feature raster and its spatial SHAP contribution."""
    apply_style()
    fig, axes = plt.subplots(1, 2, figsize=(9.6, 4.4))
    label = result.feature_labels.get(feature, feature)
    idx = result.stack.names.index(feature)
    arr = np.where(result.stack.valid_mask, result.stack.data[idx], np.nan)
    im0 = _draw_layer(axes[0], arr, result.stack, SEQUENTIAL_CMAP)
    _format_axes(axes[0], result.stack)
    axes[0].set_title(f"(a) {label} (input)", loc="left")
    fig.colorbar(im0, ax=axes[0], fraction=0.046, pad=0.03).set_label(label, fontsize=8)
    lim = _symmetric_limit([result.layers[feature]])
    im1 = _draw_layer(axes[1], result.layers[feature], result.stack, DIVERGING_CMAP,
                      norm=TwoSlopeNorm(vmin=-lim, vcenter=0, vmax=lim))
    _format_axes(axes[1], result.stack)
    axes[1].set_title(f"(b) Spatial contribution of {label}", loc="left")
    fig.colorbar(im1, ax=axes[1], fraction=0.046, pad=0.03).set_label(
        f"SHAP value ({result.shap.output_space} units)", fontsize=8)
    if result.stack.is_north_up:
        add_north_arrow(axes[1])
    add_scale_bar(axes[1], result.stack)
    _footnote(fig, result.stack, source, "The same value of a feature can contribute differently in different places.")
    fig.tight_layout()
    if path is not None:
        save_figure(fig, path, formats=formats, close=False)
    return fig


def save_all_shap_maps(
    result: Any,
    out_dir: str | Path,
    source: str = SOURCE_SYNTHETIC,
    formats: Sequence[str] = ("png",),
) -> dict[str, Path]:
    """Write one map per feature to ``out_dir`` (PNG) and return ``{feature: path}``."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    paths: dict[str, Path] = {}
    for feat in result.feature_names:
        stem = out / f"map_{feat}_shap"
        fig = plot_shap_map(result, feat, path=stem, source=source, formats=formats)
        plt.close(fig)
        paths[feat] = stem.with_suffix(".png")
    return paths
