"""Generate docs/api.md from the public API (signatures and docstrings), so it cannot drift from the code."""

from __future__ import annotations

import importlib
import inspect
from pathlib import Path

PACKAGES = ["models", "io", "datasets", "metrics", "validation", "explainers", "spatial", "visualization", "workflows",
            "utils"]


def _first_para(obj) -> str:
    doc = inspect.getdoc(obj) or ""
    return doc.split("\n\n")[0].replace("\n", " ").strip()


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    lines = ["# API reference", "",
             "Generated by `scripts/build_api_docs.py` from the public API (`__all__` of each sub-package). "
             "Top-level shortcuts are available from `geoxplain` itself.", ""]
    for pkg in PACKAGES:
        mod = importlib.import_module(f"geoxplain.{pkg}")
        lines += [f"## `geoxplain.{pkg}`", "", _first_para(mod), ""]
        for name in getattr(mod, "__all__", []):
            obj = getattr(mod, name)
            if inspect.isclass(obj):
                try:
                    sig = str(inspect.signature(obj))
                except (TypeError, ValueError):
                    sig = "(...)"
                lines += [f"### class `{name}{sig}`", "", _first_para(obj), ""]
                for mname, member in inspect.getmembers(obj):
                    if mname.startswith("_") or not (inspect.isfunction(member) or isinstance(inspect.getattr_static(obj, mname), property)):
                        continue
                    if isinstance(inspect.getattr_static(obj, mname), property):
                        lines.append(f"* `.{mname}` (property): {_first_para(member)}")
                    else:
                        lines.append(f"* `.{mname}{inspect.signature(member)}`: {_first_para(member)}")
                lines.append("")
            elif callable(obj):
                lines += [f"### `{name}{inspect.signature(obj)}`", "", _first_para(obj), ""]
            else:
                lines += [f"### `{name}`", "", f"Constant of type `{type(obj).__name__}`.", ""]
    (root / "docs" / "api.md").write_text("\n".join(lines).replace("self, ", "").replace("(self)", "()") + "\n")
    print("wrote docs/api.md")


if __name__ == "__main__":
    main()
