"""Model comparison with random vs spatial validation and an HTML report (no raster step).

Run from the repository root:  python examples/model_comparison/run.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import matplotlib  # noqa: E402

matplotlib.use("Agg")
import pandas as pd  # noqa: E402
from _common import DATA, FEATURES, out_dir, require_data  # noqa: E402

from geoxplain import ExperimentConfig, build_report, run_experiment  # noqa: E402

require_data()
out = out_dir("model_comparison")
cfg = ExperimentConfig(
    data=str(DATA / "samples.csv"), features=FEATURES, crs="EPSG:32645", out_dir=str(out),
    models=["random_forest", "xgboost", "lightgbm", "mlp"], primary_model="random_forest",
    n_splits=5, shap_samples=200, raster=None, dataset_label="Synthetic example data generated by GeoExplain (not real observations)",
)
index = run_experiment(cfg)
report = build_report(out)
opt = pd.read_csv(out / index["tables"]["validation_optimism"])
print(opt[opt.metric == "roc_auc"].round(3).to_string(index=False))
print("Report:", report)
